# Generated by Django 5.0.6 on 2024-05-12 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especialista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=20)),
                ('apellidos', models.CharField(max_length=20)),
                ('especialidad', models.CharField(max_length=30)),
                ('sexo', models.CharField(max_length=10)),
                ('cedula', models.CharField(max_length=20)),
            ],
        ),
    ]
