# Generated by Django 5.0.6 on 2024-05-12 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=20)),
                ('apellidos', models.CharField(max_length=20)),
                ('edad', models.IntegerField()),
                ('sexo', models.CharField(max_length=15)),
                ('domicilio', models.CharField(max_length=35)),
                ('peso', models.IntegerField(null=True)),
                ('estatura', models.IntegerField(null=True)),
                ('fumador', models.BooleanField(null=True)),
                ('fecha_alta', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
