# Generated by Django 5.0.6 on 2024-05-12 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='años_fumando',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='dieta',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='fumador',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
