# Generated by Django 5.0.6 on 2024-05-15 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0002_paciente_años_fumando_paciente_dieta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='prioridad',
            field=models.IntegerField(null=True),
        ),
    ]
