# Generated by Django 5.0.6 on 2024-05-15 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0003_paciente_prioridad'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='riesgo',
            field=models.IntegerField(null=True),
        ),
    ]
