# Generated by Django 5.0.6 on 2024-05-15 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0004_paciente_riesgo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='años_fumando',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
