# Generated by Django 5.0.6 on 2024-05-15 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0005_alter_paciente_años_fumando'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='no_historia_clinica',
            field=models.IntegerField(null=True),
        ),
    ]
