# Generated by Django 5.0.6 on 2024-05-16 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0002_remove_consulta_paciente'),
        ('paciente', '0006_paciente_no_historia_clinica'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='consulta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='consulta.consulta'),
            preserve_default=False,
        ),
    ]
